### ISSUE TITLE
Running cfndsl on the example files

### ISSUE THREAD

**Issue by yumpy** [neillturner/cfndsl_examples#1]
Neil, you've done a great job in converting the sample json templates using cfn2dsl. I think files would be a good basis for a comprehensive test suite for cfndsl. 

I note that the original source json templates from AWS are not in a 100% valid format for stack deployment as they contain many unresolved references. This means that the example cfndsl files also have these unresolved references and cfndsl cannot be used to generate the CF json template.

I took a copy of "EC2instance.rb" and replaced the unresolved references with either a string or with a reference to another resource that is defined in the same cfndsl file. This seemed to do the trick but this means that the generated json file does not 100% match the original json file.

Just wondering if you had any thoughts on how to tidy up the original json template snippets?

**Comment by neillturner** [comment]
all good thoughts. Currently i going to add a whole lots more AWS sample cloudformation templates. 
I guess i created them for myself to help me in development.
